apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/open-telemetry/opentelemetry-operator/tree/main/config/default
images:
- name: controller
  newName: quay.io/opentelemetry/opentelemetry-operator
  newTag: v0.45.0
